site_name: OGC EDR Service Profile Generator
site_description: Authoritative tooling for creating OGC API - EDR Part 3 Service Profiles
site_author: Shane Mill
repo_url: https://github.com/ShaneMill1/OGC-Service-Profile-Creation
repo_name: ShaneMill1/OGC-Service-Profile-Creation

docs_dir: .

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Home: README.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
